producer:
  image: ghcr.io/cloudforged11/kafka-k8s-pipeline/producer:latest
  replicas: 1

consumer:
  image: ghcr.io/cloudforged11/kafka-k8s-pipeline/consumer:latest
  replicas: 1

kafka:
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  topic: sample-events
  consumerGroupId: sample-consumer-group
